//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.WebResources.WebResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.WebResources.WebResources.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить&gt;&gt;.
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить e-mail.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно изменили email. &lt;a href=&apos;javascript:void(0);&apos; id=&apos;closeChangedEmailMessage&apos;&gt;Закрыть&lt;/a&gt;.
        /// </summary>
        public static string ChangeEmailSuccess {
            get {
                return ResourceManager.GetString("ChangeEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверте правильность ввода пароля.
        /// </summary>
        public static string CheckPassword {
            get {
                return ResourceManager.GetString("CheckPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы отправили на указаный адрес письмо со ссылкой для подтверждение смены email. &lt;a href=&apos;javascript:void(0);&apos; id=&apos;closeConfirmMessage&apos;&gt;Закрыть&lt;/a&gt;.
        /// </summary>
        public static string ConfirmChangeEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmChangeEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно изменили пароль. &lt;a href=&apos;javascript:void(0);&apos; id=&apos;closeConfirmMessage&apos;&gt;Закрыть&lt;/a&gt;.
        /// </summary>
        public static string ConfirmChangePassword {
            get {
                return ResourceManager.GetString("ConfirmChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль:.
        /// </summary>
        public static string ConfirmPassword1 {
            get {
                return ResourceManager.GetString("ConfirmPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно активировали свой email..
        /// </summary>
        public static string Email_Activation_success {
            get {
                return ResourceManager.GetString("Email_Activation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email_DisplayName {
            get {
                return ResourceManager.GetString("Email_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string Email_DisplayName1 {
            get {
                return ResourceManager.GetString("Email_DisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт не активирован, для активации необходимо пройти по ссылке отправленой на Ваш e-mail указанный в регистрации..
        /// </summary>
        public static string EmailActivationLink {
            get {
                return ResourceManager.GetString("EmailActivationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким адресом уже зарегистрирован..
        /// </summary>
        public static string EmailAllreadyExists {
            get {
                return ResourceManager.GetString("EmailAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой e-mail уже есть в базе. Войдите под своим именем или воспользуйтесь восстановлением пароля..
        /// </summary>
        public static string EmailAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("EmailAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail указан с ошибкой.
        /// </summary>
        public static string ErrorIncorrectEMailFormat {
            get {
                return ResourceManager.GetString("ErrorIncorrectEMailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали неправильный код смены email.
        /// </summary>
        public static string ErrorInvaildCodeChangeEmail {
            get {
                return ResourceManager.GetString("ErrorInvaildCodeChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали неправильный код восстановления пароля.
        /// </summary>
        public static string ErrorInvaildCodeChangePassword {
            get {
                return ResourceManager.GetString("ErrorInvaildCodeChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время регистрации произошла ошибка - попробуйте зарегистрироваться позже..
        /// </summary>
        public static string ErrorWhileRegistering {
            get {
                return ResourceManager.GetString("ErrorWhileRegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string FilterSettings_SaveButtonText {
            get {
                return ResourceManager.GetString("FilterSettings_SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя:.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы давно зарегистрировались и забыли пароль? Введите e-mail с которым вы регистрировались на нашем сайте. Мы пришлем вам письмо со ссылкой для восстановления пароля.
        /// </summary>
        public static string ForgotPasswordInfo {
            get {
                return ResourceManager.GetString("ForgotPasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия:.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Login_DisplayName {
            get {
                return ResourceManager.GetString("Login_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин:.
        /// </summary>
        public static string Login_DisplayName1 {
            get {
                return ResourceManager.GetString("Login_DisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин занят.
        /// </summary>
        public static string LoginIsBusy {
            get {
                return ResourceManager.GetString("LoginIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подождите {0} минут.
        /// </summary>
        public static string MaxAttemptsLogin {
            get {
                return ResourceManager.GetString("MaxAttemptsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО.
        /// </summary>
        public static string Name_DisplayName {
            get {
                return ResourceManager.GetString("Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword_DisplayName {
            get {
                return ResourceManager.GetString("NewPassword_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль:.
        /// </summary>
        public static string NewPassword_DisplayName1 {
            get {
                return ResourceManager.GetString("NewPassword_DisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        public static string OldPassword_DisplayName {
            get {
                return ResourceManager.GetString("OldPassword_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль:.
        /// </summary>
        public static string OldPassword_DisplayName1 {
            get {
                return ResourceManager.GetString("OldPassword_DisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пароль.
        /// </summary>
        public static string Password_DisplayName {
            get {
                return ResourceManager.GetString("Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        public static string Password_DisplayName1 {
            get {
                return ResourceManager.GetString("Password_DisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пароль должен быть не более 50 символов.
        /// </summary>
        public static string Password_Length {
            get {
                return ResourceManager.GetString("Password_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копии пароля не совпадают.
        /// </summary>
        public static string PasswordMustMatch {
            get {
                return ResourceManager.GetString("PasswordMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка!&lt;br/&gt;Попробуйте еще раз!.
        /// </summary>
        public static string PasswordResetFailure {
            get {
                return ResourceManager.GetString("PasswordResetFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы отправили на указаный адрес письмо со ссылкой для восстановления пароля..
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно изменили пароль.
        /// </summary>
        public static string PasswordRestoredSuccess {
            get {
                return ResourceManager.GetString("PasswordRestoredSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон:.
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно изменили свои данные.
        /// </summary>
        public static string ProfileInfoSaveSuccess {
            get {
                return ResourceManager.GetString("ProfileInfoSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string ProfileSaveBtnText {
            get {
                return ResourceManager.GetString("ProfileSaveBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким адресом уже зарегистрирован. Вы давно регистрировались и забыли пароль? &lt;a href=&quot;javascript:void(0);&quot; id=&quot;lnkResetPassword&quot;&gt;Восстановить пароль&lt;/a&gt;.
        /// </summary>
        public static string Register_AllreadyExists {
            get {
                return ResourceManager.GetString("Register_AllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string RegisterButtonText1 {
            get {
                return ResourceManager.GetString("RegisterButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Добро пожаловать!&lt;/p&gt;Вы успешно зарегистрировались в системе бронирования отелей Oktogo.ru.
        /// </summary>
        public static string Registration_Success {
            get {
                return ResourceManager.GetString("Registration_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration1 {
            get {
                return ResourceManager.GetString("Registration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация прошла успешно, но войти в систему не удалось - попробуйте войти в систему позже.
        /// </summary>
        public static string RegistrationSucceededButUnableToLogin {
            get {
                return ResourceManager.GetString("RegistrationSucceededButUnableToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить пароль.
        /// </summary>
        public static string RestorePassword {
            get {
                return ResourceManager.GetString("RestorePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отправить.
        /// </summary>
        public static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string Validation_ConfirmPassword_Required {
            get {
                return ResourceManager.GetString("Validation_ConfirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите E-mail.
        /// </summary>
        public static string Validation_Email_Required {
            get {
                return ResourceManager.GetString("Validation_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя можно вводить только латинскими буквами.
        /// </summary>
        public static string Validation_FirstName_OnlyLatin {
            get {
                return ResourceManager.GetString("Validation_FirstName_OnlyLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилию можно вводить только латинскими буквами.
        /// </summary>
        public static string Validation_LastName_OnlyLatin {
            get {
                return ResourceManager.GetString("Validation_LastName_OnlyLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string Validation_Password_Required {
            get {
                return ResourceManager.GetString("Validation_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный код подтверждения смены email. &lt;a href=&apos;javascript:void(0);&apos; id=&apos;closeConfirmMessage&apos;&gt;Закрыть&lt;/a&gt;.
        /// </summary>
        public static string WrongConfirmChangeEmail {
            get {
                return ResourceManager.GetString("WrongConfirmChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким e-mail не зарегистрирован.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to логин или пароль неверен.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
