//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.WebResources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.WebResources.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильное имя пользователя или пароль.
        /// </summary>
        public static string AccountController_Account_Saving_Profile_Error {
            get {
                return ResourceManager.GetString("AccountController_Account_Saving_Profile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка входа в систему. Обратитесь в службу технической поддержки.
        /// </summary>
        public static string AccountController_Login_Error {
            get {
                return ResourceManager.GetString("AccountController_Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильное имя пользователя или пароль.
        /// </summary>
        public static string AccountController_Login_PasswordOrLogin_Invalid {
            get {
                return ResourceManager.GetString("AccountController_Login_PasswordOrLogin_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка регистрации фирмы: .
        /// </summary>
        public static string AccountController_Register_Error_Register {
            get {
                return ResourceManager.GetString("AccountController_Register_Error_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to байт.
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смена email на сайте {0}.
        /// </summary>
        public static string ChangeEmailText {
            get {
                return ResourceManager.GetString("ChangeEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смена пароля на сайте {0}.
        /// </summary>
        public static string ChangePasswordSubject {
            get {
                return ResourceManager.GetString("ChangePasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка активации e-mail. Попробуйте позднее или перезвоните в службу технической поддержки.
        /// </summary>
        public static string EmailActivationCodeFailure {
            get {
                return ResourceManager.GetString("EmailActivationCodeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На Вашу почту {0} было отправлено письмо со ссылкой активации email.&lt;a href=&quot;{1}&quot;&gt;Отправить еще&lt;/a&gt;.
        /// </summary>
        public static string EmailActivationCodeSend {
            get {
                return ResourceManager.GetString("EmailActivationCodeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время отправки кода ссылки активации произошла ошибка. Попробуйте позднее или перезвоните в службу технической поддержки.
        /// </summary>
        public static string EmailActivationCodeSendFailure {
            get {
                return ResourceManager.GetString("EmailActivationCodeSendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На Вашу почту {0} было отправлено письмо со ссылкой активации email.&lt;a href=&quot;{1}&quot;&gt;Отправить еще&lt;/a&gt;.
        /// </summary>
        public static string EmailActivationCodeSendSuccess {
            get {
                return ResourceManager.GetString("EmailActivationCodeSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код активации неверный.
        /// </summary>
        public static string EmailActivationInvalid {
            get {
                return ResourceManager.GetString("EmailActivationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активация e-mail на сайте {0}.
        /// </summary>
        public static string EmailActivationSubject {
            get {
                return ResourceManager.GetString("EmailActivationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно активировали e-mail.
        /// </summary>
        public static string EmailActivationSuccess {
            get {
                return ResourceManager.GetString("EmailActivationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчитать.
        /// </summary>
        public static string Filter_Button_Calculate {
            get {
                return ResourceManager.GetString("Filter_Button_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сформировать отчет.
        /// </summary>
        public static string Filter_Button_DoReport {
            get {
                return ResourceManager.GetString("Filter_Button_DoReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать количество записей.
        /// </summary>
        public static string Filter_Button_ShowRowsCount {
            get {
                return ResourceManager.GetString("Filter_Button_ShowRowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о грузополучателе.
        /// </summary>
        public static string Filter_CargoRecipientInfo {
            get {
                return ResourceManager.GetString("Filter_CargoRecipientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о грузоотправителе.
        /// </summary>
        public static string Filter_CargoSenderInfo {
            get {
                return ResourceManager.GetString("Filter_CargoSenderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевозимый груз.
        /// </summary>
        public static string Filter_CargoType {
            get {
                return ResourceManager.GetString("Filter_CargoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация.
        /// </summary>
        public static string Filter_DopInfo {
            get {
                return ResourceManager.GetString("Filter_DopInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РАССТОЯНИЕ ПЕРЕВОЗКИ.
        /// </summary>
        public static string Filter_DopInfo_DestinationKm {
            get {
                return ResourceManager.GetString("Filter_DopInfo_DestinationKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to номера вагонов / конетейнеров / документов / даты.
        /// </summary>
        public static string Filter_DopInfo_FourColumns {
            get {
                return ResourceManager.GetString("Filter_DopInfo_FourColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРОВОЗНАЯ ПЛАТА (БЕЗ НДС).
        /// </summary>
        public static string Filter_DopInfo_PayWay {
            get {
                return ResourceManager.GetString("Filter_DopInfo_PayWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОННО-КИЛОМЕТРЫ.
        /// </summary>
        public static string Filter_DopInfo_TonnKm {
            get {
                return ResourceManager.GetString("Filter_DopInfo_TonnKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОБЪЕМ ПЕРЕВОЗКИ ТОНН.
        /// </summary>
        public static string Filter_DopInfo_VolumeTonn {
            get {
                return ResourceManager.GetString("Filter_DopInfo_VolumeTonn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период перевозки.
        /// </summary>
        public static string Filter_PeriodTransportation {
            get {
                return ResourceManager.GetString("Filter_PeriodTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор полей отчета.
        /// </summary>
        public static string Filter_SelectionFieldReport {
            get {
                return ResourceManager.GetString("Filter_SelectionFieldReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сведения о поставке.
        /// </summary>
        public static string Filter_TranspportationInfo {
            get {
                return ResourceManager.GetString("Filter_TranspportationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подвижной состав.
        /// </summary>
        public static string Filter_VatonType {
            get {
                return ResourceManager.GetString("Filter_VatonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маршрут перевозки.
        /// </summary>
        public static string Filter_WayTranspportation {
            get {
                return ResourceManager.GetString("Filter_WayTranspportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид перевозки.
        /// </summary>
        public static string FilterColumn_TransportationType {
            get {
                return ResourceManager.GetString("FilterColumn_TransportationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КБ.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МБ.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин должен быть от 6 до 12 символов.
        /// </summary>
        public static string RegisterViewModel_Login_Логин_Length {
            get {
                return ResourceManager.GetString("RegisterViewModel_Login_Логин_Length", resourceCulture);
            }
        }
    }
}
